### ISSUE TITLE
Dynamic component id not correctly registered

### ISSUE THREAD

**Issue by daanbroekhuizen** [B-3PO/angular-material-expansion-panel#14]
Whenever I try to dynamically assign an id to a panel it gets registered with the literal string instead of the dynamic one. Example:

```
<md-expansion-panel ng-repeat="section in indexCtrl.menu" md-component-id="{{'panel_' + $index}}">

</md-expansion-panel>
```

Will give all the panels the literal string "panel_$index" as id making it in inaccessible through the $mdExpansionPanel service.

**Comment by B-3PO** [comment]
I will look into this over the weekend

**Comment by B-3PO** [comment]
fixed in new version
