### ISSUE TITLE
Missing "main" property in package.json

### ISSUE THREAD

**Issue by tomdrewes** [B-3PO/angular-material-expansion-panel#16]
Really looking forward to trying this out in a project!  However, we're using browserify, and the package.json file seems to be missing a "main" property.  Adding something like this should take care of the issue with browserify:

"main": "dist/md-expansion-panel.js"

https://docs.npmjs.com/files/package.json#main

Thanks for creating this component!

**Comment by B-3PO** [comment]
If you confirm this fix for me that would be great. Install the Features/Issues/#16 branch and let me know if that fixes, then i will release a new version

**Comment by tomdrewes** [comment]
Tested and looks good.  Thanks for the quick response!

**Comment by B-3PO** [comment]
released
