### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by letthewookieewin** [B-3PO/angular-material-expansion-panel#21]
Not an issue with the code, just having some troubles implementing it. Can you post your example code?

**Comment by henzler** [comment]
He provided example code in his READ.me! I do not get your question?

[(https://github.com/B-3PO/angular-material-expansion-panel)]

**Comment by B-3PO** [comment]
you can also download the repo and run `gulp`. that will startup an example running on localhost:8080, I will try to get the github.io pages working for the example

**Comment by B-3PO** [comment]
https://b-3po.github.io/angular-material-expansion-panel
