### ISSUE TITLE
Method for finding open panels

### ISSUE THREAD

**Issue by davidkaneda** [B-3PO/angular-material-expansion-panel#25]
I see there's a panel.isOpen method, but from a panelGroup, afaics, there's no way to find the open panel instance (or panels, in the case of multiple="true").

Similarly, would be great if you could call collapse on a group to close all open panels in it.

Thanks!

**Comment by B-3PO** [comment]
Good ideas, i will add these methods

**Comment by B-3PO** [comment]
Check out the newest release
