### ISSUE TITLE
How to destroy a already registered $mdExpansionPanelGroup

### ISSUE THREAD

**Issue by dcoferraz** [B-3PO/angular-material-expansion-panel#26]
I need to destroy the whole $mdExpansionPanelGroup in order to update it.

How do I do this?

**Comment by B-3PO** [comment]
I'm not clear on what you mean by "destroy", but here are some things that may help.
- You can use the `removeAll` method

``` javascript
$mdExpansionPanelGroup('theComponentId').removeAll();
```
- You can remove the group element from the DOM. This will remove and destroy all panels.

**Comment by B-3PO** [comment]
Will close this after 30 days of no response

**Comment by B-3PO** [comment]
Closed due to inactivity
