### ISSUE TITLE
ng-disabled is not working on md-expansion-panel

### ISSUE THREAD

**Issue by zivoradmilekic** [B-3PO/angular-material-expansion-panel#27]
ng-disabled is not working on md-expansion-panel, but disabled="disabled " is working. I need ng-disabled in my app. Please help!

**Comment by B-3PO** [comment]
I'll look at it, thanks

**Comment by zivoradmilekic** [comment]
Hi @B-3PO what is status with this issue? My colleague and I tried to solve it but did not have a luck. I hope you had more success since this is your directive.

**Comment by zivoradmilekic** [comment]
Hi @B-3PO I almost finished implementation of ng-disabled in your directive. Soon I will make pull request from my forked repo. I hope you will like it and marge it, because my company is waiting for ng-disabled in bower component.

**Comment by B-3PO** [comment]
Hey, i put up a pr with the fix and tests. Please test with this pr and confirm these changes fix your issue, then i will publish a new version.
https://github.com/B-3PO/angular-material-expansion-panel/pull/29

**Comment by B-3PO** [comment]
merged, will be released with next version
