### ISSUE TITLE
Cannot Find md-component-id

### ISSUE THREAD

**Issue by michael-learns** [B-3PO/angular-material-expansion-panel#35]
Hi! I'm currently trying this out however it keeps giving me this error

`ExpansionPanel 'panelOne' is not available! Did you use md-component-id='panelOne'?
angular.js:14328 TypeError: Cannot read property 'expand' of undefined`

I've imported all necessary modules such as

1. Angular Material
2. Angular Arial
3. Angular Messages
4. Angular Animate
5. Angular Material Expansion Panel

And my template I just copied from the trial template. I have md-component-id set as panelOne but still I'm getting this error .

**Comment by NHMD** [comment]
Try calling expand async instead:
`$mdExpansionPanel().waitFor('panelOne')
 .then(function (instance) { 
   instance.expand(); 
});`

**Comment by michael-learns** [comment]
@NHMD Okay that seemed to work. However I'm getting this error now:

`TypeError: Cannot read property 'element' of null`

**Comment by michael-learns** [comment]
So now I was able to fix this by just adding this line

`$mdExpansionPanelGroup().waitFor('panelGroup').then(function (instance) {});`

I don't if that's the right way of doing it but it seemed to work for me.

**Comment by chetanku** [comment]
I am still not able to get it work. I took the master branch followed by:
npm install
gulp build
The build goes fine.
I see the js and css getting updated in the dist folder.
gulp test passes
and I get the error:

angular.js:14328 ExpansionPanel 'panelOne' is not available! Did you use md-component-id='panelOne'?
angular.js:14328 TypeError: Cannot read property 'expand' of undefined ..

any help will be great.

**Comment by nitishkumarnitc** [comment]
I am also getting the same error, please help.

angular.js:14794 ExpansionPanel 'panelOne' is not available! Did you use md-component-id='panelOne'?
