### ISSUE TITLE
Default open panel

### ISSUE THREAD

**Issue by javieerrubio11** [B-3PO/angular-material-expansion-panel#36]
Hi, 

I'm traying to create a panel that by default is opened but I have not been able to do it.

Are there any option to do it? My panel is a simple panel, it isn't a group panel.

Thnaks for all.

**Comment by B-3PO** [comment]
it depends on how you are using the panel. can you post your code

**Comment by javieerrubio11** [comment]
For example I use this code:


```
<md-expansion-panel md-component-id="panelOne">
  <md-expansion-panel-collapsed>
    <div class="md-title">Title</div>
    <div class="md-summary">Summary</div>
    <md-expansion-panel-icon></md-expansion-panel-icon>
  </md-expansion-panel-collapsed>

  <md-expansion-panel-expanded>
    <md-expansion-panel-header>
      <div class="md-title">Expanded Title</div>
      <div class="md-summary">Expanded Summary</div>
      <md-expansion-panel-icon></md-expansion-panel-icon>
    </md-expansion-panel-header>

    <md-expansion-panel-content>
      <h4>Content</h4>
      <p>Put content in here</p>
    </md-expansion-panel-content>

    <md-expansion-panel-footer>
      <div flex></div>
      <md-button class="md-warn" ng-click="$panel.collapse()">Collapse</md-button>
    </md-expansion-panel-footer>
  </md-expansion-panel-expanded>
</md-expansion-panel>
```


This code is the basic example in github from md-expansion-panel, and I don't know if I am able to configure this code to create a single panel that is expanded by default when Tt appers at the html page.

Sorry, it's difficult reproduce and example in jsfiddle for exmaple because the library isn't are online and have a lot of dependencies, however if you have a basic example in jsfiddle post the url.

Thanks for all.

**Comment by B-3PO** [comment]
you can add the open method with the expansionPanel service.
```javascript
angular.module('app').controller('ctrl', function ($mdExpansionPanel) {
  $mdExpansionPanel().waitFor('panelOne').then(function (instance) {
    instance.expand();
    instance.collapse({animation: false});
    instance.remove();
    instance.isOpen();
  });
});
```
