### ISSUE TITLE
Not closing when md-no-sticky="true"

### ISSUE THREAD

**Issue by mpeula** [B-3PO/angular-material-expansion-panel#4]
When md-no-stick="true" the initEvents() function is disabled, so the variable "scrollContainer" is never filled... That cause a javascript error when killEvents() is fired.

My temporal fix is to replace the line 218 of the expansionPanel.directive.js:

`if (scrollContainer.nodeName === 'MD-CONTENT') {`

for:

`if (scrollContainer && scrollContainer.nodeName === 'MD-CONTENT') {`

I know that maybe is not the best solution, but it works. If you can take a look at that would be perfect.
By the way... nice work!! :D

**Comment by B-3PO** [comment]
This is fixed along with the last update

**Comment by B-3PO** [comment]
Please let me know if you put up your app so i can check it out.
Thanks!

**Comment by mpeula** [comment]
Works like a charm, thanks!
