### ISSUE TITLE
Button on collapsed panel

### ISSUE THREAD

**Issue by schaib** [B-3PO/angular-material-expansion-panel#42]
Hi, 

I am trying to put a button on the md-expansion-panel-collapsed but it fires two events : 
 1- The button event
 2- Then the panel expansion 

I am trying to use the collapsed panel as a clickable md-list-item with Secondary Controls.

Thanks

**Comment by rkimaoui** [comment]
Did you tried, on click event:
 event.preventDefault();
Or
 event.stopImmediatePropagation();

**Comment by schaib** [comment]
This seems to work, thanks !
