### ISSUE TITLE
Collapse an expanded panel by clicking on the header

### ISSUE THREAD

**Issue by chenlijun99** [B-3PO/angular-material-expansion-panel#47]
It would be handy that a panel that is expanded can be collapsed by clicking on its header.
It could be achieved with `<md-expansion-panel-header ng-click="$panel.collapse()">` and proper CSS,
but having it built-in would be nice.

Something like this https://material.angular.io/components/expansion/overview

**Comment by coopernewby** [comment]
You can also just add` <md-expansion-panel-expanded ng-click="$panel.collapse()">` to the expanded panel

**Comment by chenlijun99** [comment]
Yeah, but it would nice to have into built-in, so that we can avoid to write that each time.

Anyway in a commit of mine I've added this feature. 

It would be aweosome, if you have time to review my pull-request
